### ISSUE TITLE
О проекте

### ISSUE THREAD

**Issue by Dan095ss** [hubcoreorg/hubcore.org#11]
Немного не понимаю смысл проекта(это что-то тип GitLab'а по принципу работы?
Или типа конструктора для создания проектов?)

**Comment by opencard** [comment]
Аналогично, вообще всё размыто. Кто-то будет получать деньги с фонда, набирая колеров?
Не проще использовать существующие фонды, Ubuntu например.

**Comment by Piterden** [comment]
А меня вообще забанили, когда я попросил представиться и рассказать о проекте. Вот такой вот у нас опенсорс )))

**Comment by Piterden** [comment]
Забанил меня во втором чате. Ссыкло)) Ребята не ведитесь. Этот трус вас никуда не приведет!!!

**Comment by Piterden** [comment]
![image](https://user-images.githubusercontent.com/5930429/65691105-f3a6c100-e078-11e9-9777-fbb384d77344.png)

**Comment by gtdevice** [comment]
Для начала им стоит вложиться в описание проекта и сделать что-то отличное от уровня первого курса института

**Comment by hubcoreadmin** [comment]
Мы сейчас сделаем основные экраны, думаю понятнее станет. Над проектом сейчас работает несколько человек реально. Остальные пока только критикуют.  Добавил пункт в манифест специально относительно токсичных персон. Бан сразу без предупреждения с удалением всех сообщений. Для людей кто настроен агрессивно к сообществу, у нас только такой Опен Сурс =)
