### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by d9k** [hubcoreorg/hubcore.org#12]
Предлагаю рассмотреть Lua, как самый простой в изучении и приятный для чтения язык :)
(осложнения может вызвать только концепт метатаблиц, но за пару недель можно овладеть им в совершенстве)

база данных tarantool (разработка от mail.ru), а фреймворк может быть, например, lapis

Браузерная часть может быть vue + fengari. Но полноценной отладки  пока нет

https://learnxinyminutes.com/docs/ru-ru/lua-ru/

https://www.tarantool.io/ru/doc/2.2/book/box/data_model/#space

https://leafo.net/lapis/

https://twitter.com/hashtag/fengari

https://twitter.com/giann/status/1114786114475368448

https://t.me/LuaLang
https://t.me/ProLua

**Comment by vosart** [comment]
Зачем, если есть уже замечательный Python

**Comment by d9k** [comment]
@vosart, спорно, что он замечательный)
Питон кажется простым, кажется изящным, но это не так

**Comment by d9k** [comment]
@vosart, неоспоримые плюсы пайтона 

1) Под него есть пакеты на любой случай жизни (однако часто низкого качества, с кучей зависимостей, требующие допиливания и многочасового разбора спагетти-кода). 
2) Его популярность стабильно растёт, см. tiobe.com/tiobe-index/

**Comment by hubcoreadmin** [comment]
Чем популярнее язык, тем проще найти разработчиков =)

**Comment by mymtw** [comment]
> @vosart, неоспоримые плюсы пайтона
> 
> 1. Под него есть пакеты на любой случай жизни (однако часто низкого качества, с кучей зависимостей, требующие допиливания и многочасового разбора спагетти-кода с помощью качественной IDE вроде PyCharm).
> 2. Его популярность стабильно растёт, см. http://www.tiobe.com/tiobe-index/

3.приложения пишутся быстрее чем на чем-то другом

А какие есть ORM под Lua? а есть вот как sqlalchemy например?
про использование tarantool это для каких целей можно узнать?

**Comment by stellarbear** [comment]
C#/F#, ну или React+TS+GraphQL
